clean:

	rm *.aux;
	rm *.bbl;
	rm *.blg;
	rm *.log;
	rm *.nlo;
	rm *.out;
	rm *.gz;
	rm *.toc;
	rm *.lof;
	rm *.lot;
	rm chapters/*.aux;
	rm chapters/*.log;
	rm chapters/pseudocode/*.aux;
	rm listings/*.aux;
